osx_image: xcode7.3
language: objective-c
script:
- xcodebuild clean build -workspace Memz.xcworkspace -scheme 'Memz' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
